### ISSUE TITLE
Anki 2.1.29 Incompatibility

### ISSUE THREAD

**Issue by spartandrew18** [lovac42/Fanfare#14]
![image](https://user-images.githubusercontent.com/66539077/88722413-34d28c00-d0f5-11ea-86b5-30261013718d.png)

When loading up a deck this occurs:

Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.29 (bbff62bf) Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
Platform: Windows 10
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2020-07-28 16:45:17

Caught exception:
Traceback (most recent call last):
  File "aqt\progress.py", line 43, in handler
  File "C:\Users\Andrew\AppData\Roaming\Anki2\addons21\2073603704\fanfare.py", line 136, in <lambda>
    mw.progress.timer(self.duration,lambda:self._nextCard(r,_old),False)
  File "C:\Users\Andrew\AppData\Roaming\Anki2\addons21\2073603704\fanfare.py", line 143, in _nextCard
    self.fb.stop()
AttributeError: 'Fanfare' object has no attribute 'fb'

**Comment by spartandrew18** [comment]
Can you fix? pretty please.

**Comment by samawelch** [comment]
I can't offer you any actual fixes, but if it's important to you that this add-on still works, why not downgrade to 2.1.26?
