### ISSUE TITLE
This shared item is no longer available.

### ISSUE THREAD

**Issue by Jfaler** [lovac42/Fanfare#16]
Hey I noticed the addon was removed. Is this permanent? https://ankiweb.net/shared/info/2073603704

**Comment by lovac42** [comment]
As stated in the release page. https://github.com/lovac42/Fanfare/releases
This addon will cause issues for future versions of Anki and requires a rewrite.

**Comment by Jfaler** [comment]
> 
> 
> As stated in the release page. https://github.com/lovac42/Fanfare/releases
> This addon will cause issues for future versions of Anki and requires a rewrite.

Thanks I read the release. I just happened to notice the removal.

**Comment by galantra** [comment]
As a replacement I suggest the add-on [Hitmarkers](https://ankiweb.net/shared/info/1776869150). I don't know if future Anki versions will break Hitmarkers.
