### ISSUE TITLE
Ankiweb page

### ISSUE THREAD

**Issue by AnKingMed** [lovac42/Fanfare#17]
I noticed this is no longer on ankiweb and had someone ask me about it. Are you looking to transfer this to a new maintainer? If so I would be willing to do that

**Comment by lovac42** [comment]
Given the changes, it would be faster and cost less to maintain if you write a new one from scratch. This was documented in the release pages.

**Comment by AnKingMed** [comment]
Ok thanks for the info

**Comment by lovac42** [comment]
btw I plan to rewrite these for 2.2 if the API is more stable. So don't use the same title if you work on something similar.

My guess is Qt5 -> Qt6 -> Electron. There will be multiple changes coming. GL.

**Comment by Cubicle13** [comment]
When is Anki 2.2 planned?

**Comment by lovac42** [comment]
It's hypothetical... But that's the direction Anki is moving towards.

**Comment by Cubicle13** [comment]
That would mean that your planned rewrite would be hypothetical as well; are you okay with me or AnKingMed rewriting it now (under a different name)? Really big fan your work btw!

**Comment by lovac42** [comment]
Knock yourselves out. I also take PRs if you like to help out, but not for this addon since it requires a rewrite.
