### ISSUE TITLE
Cant install Fanfare on Anki 2.1.20

### ISSUE THREAD

**Issue by Willz7** [lovac42/Fanfare#7]
![2020-02-27 12_09_18-Window](https://user-images.githubusercontent.com/5053219/75443786-0be97780-595a-11ea-8972-c79fc486671a.png)

I can't install Anki Fanfare, and I'm still getting the above error

**Comment by lovac42** [comment]
Fanfare works upto anki 2.1.16. There were too many changes made to anki after that.

FYI, addons are now version specific.

**Comment by lovac42** [comment]
https://github.com/lovac42/Fanfare/releases
