### ISSUE TITLE
Break intermission from time rather than cards

### ISSUE THREAD

**Issue by spartandrew18** [lovac42/Fanfare#9]
I love this addon!

Is there a way to set the break intermission after a certain amount of time rather than a certain amount of cards? If I wanted to do the Pomodoro schedule so 50 minutes of cards and then it hits me with a 10 min break intermission would this be possible in a future update?

Best,
Andrew

**Comment by lovac42** [comment]
You can disable intermission and use LifeDrain for that.

As I noted on the release page, this addon uses old hooks that might cause conflict issues or stop working in future versions of Anki. It is likely that I might break this into smaller addons rather than add more features. I haven't decided.

**Comment by spartandrew18** [comment]
Hi lovac42,

So I have actually been using the lifedrain addon as a 50-minute timer by setting it to 3000 max life. I have contacted the author of lifedrain to try and incorporate a break option where the lifedrain progress bar basically goes in a gaining fashion so left to right for let's say 10 minutes. I thought of having that gaining progress line up with fanfare's intermission setting would make an awesome pair together. This is why I wanted to see if you could add an option for intermission after a set amount of time.

So if I start studying a deck for 50 minutes as soon as the 50 minutes passes im booted into an intermission break with the break picture and while I'm waiting, my lifedrain bar is gaining for 10 minutes. Then after the 10 minutes, I could continue studying again by clicking the break is over button in fanfare.

If this is too much to ask for I completely understand!

Thank you for making this awesome addon once again, it really helps with my studies!

Best,
Andrew
